######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
  - oraclejdk13

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###############
### Caching ###
###############
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#################
### SonarQube ###
#################
addons:
  sonarcloud:
    organization: "d3adspace"
    token:
      secure: fbzOLyAVkydroPbUQVXgiLHTWH8/kq0BxB51OEuFKd+H/FQoR68Pjc2bor1LA6gw35SIQwlffsVE3WN1cqWkAELKnhDqJHeR/+8bsjCdhx+eG4Gm9ixUTCh/5k/oTngOrJ7baH7Ln75jcqXI65ry6fnzfMJ93K9gmmMJ8pQMZCquh3dxp/GuzLx8j4SiLfPKiWAfptExKNBPm7CSFBm2QbBbvQ3whq3PEKhNpa4U1RHOFqVWauXpABRTRhpkUVdBIFraWn52HoTC4DUvw57tkRrFZy8oLXXz+D95xZ72ffjt4pySBlIhe/IKixR4EkmAaSAjP8V/h5kwQhcT9dmgV098wOBtJOp2V6NMJ31syJSi6IR/Y4WXxxSvYDSoS4BYXEULTef53sHrHuNw5J1v1XNtR8+TAA01Rw8fbC1WhQMoIUG8+BA1iQoS5y02in1zroqX4ig/FTnOJ2Vn1PSDj8q0FpCBquVNWjOgGWvNGQ5S8mfGzLccgTJw+SAYhYvIWXHGoQ9BVKGsRWk0Oi41nphn65Z2vIU9ugr+n6db4eU7TyP0PQKPVyX90OA2P4MDr1sMTlIxxG8dpRnl6PMrYpHLkGscrWAv3B+BF0VCwKdiiujqoH+IqzRKsobxjiRvIG97nzwWLqm9PVmV4O8kReJ2nzcelHhauU082bdlNCw=

###########################
### Actual Build Script ###
###########################
script:
  - ./gradlew build test
  - ./gradlew --scan -s
  - ./gradlew codeCoverageReport
  - ./gradlew sonarqube

###################################
### Upload Code Coverage Report ###
###################################
after_success:
  - bash <(curl -s https://codecov.io/bash)

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew publish
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    - secure: pUStloSdx6cNK6Pcsp2Wj7piIvX5u26vu8f2f5eecVewObhkW29yiVtP17aXtwETbZPxfv3F+G8yeEeEgV8tYAE4o2BKUcr0chOxXGSBKlrs6kkdJQo7XwBxdYE8kvKqjcAWx7CBXDZssCyvSZU9V0mZxTYDMXzA0qaFUzCsEV1decx+Jc8gpL4MqcE9z8/dsammYBTV39Gla2wJbKI5iY5S5dWMzVUlXuiYIIiUrUurHLta8oTkpJ7VBQsSHcZ7gPPOsN2E5XcuZk9gkNoJlZJu8mtu/mkwOZLz2g4GZ65hUuWwNYUkjNCeBXUGAIuf/X7gyKWVmwsG6eO07dasBgd93fGN8PyVcXZWZYI8jQd4WhS2e+xf+REH4UOEFcydSAvnKoeBo03PXYpREzY4QI37by7TKCdtutxVFpTDpm3awxOugd9IPNAzNJ/foRhiHpT1BxbLKirkjnneHERXHkDsOQC0Vgq8ihZRTyJVuXYQltBwau69kIxpCFWk1lhBXRu7Yvnva52+r0oIz6IcvUX9k+yFVVSuVxevc7MHZBEx54FNlG+lblwH8peYQij7i4My2+SgKXYZXgEpEwXM3e2hUpBsbZHRBpIH140YPwI0I3LV5ZRS5Q/jTJDqJjjfMDFW0E2WTbJEenIA30rWTIxHCc+DRHDUTeNz07uMDTI=
    - secure: bNszyk4/NP6VmgJbWRTfiWYL9uzaso0KsXK5zHoHkfea4gCEaWfUwi8bmErJXZnGdLizQa2qlEvIRmKn5z0SBvjo2NkM/5HiO4/6xeJLsH9pC6WPVcBhf6NFcIOt+2VcXpIfKFUbjmt/r+GSVxGGv6jBan8G7mEBif/CmjKenq8n1GPoXCWVFgv33XEQraDMcLpPu0mQMMkfVQYR+gp6hgzw+z9mtg0xAaKcFS4fwjyujnH/oIsZ3U40HyUvU2+AZ34pomkhBxu9VcZ4q7f1+v7dzCOzgUeb9hyuHWrJIJgQC0KEC5LiNJc6Xh52s5ETyzMal0kncQpyBdK67dqK4D/JXN2fDjDNOBPFFEEy7uAtPMOnnFyorLL28LBYsPmMgc/jW3u2lB8q7J8OBr4cjS4jF6e8PIoj3eVx8j0t04qd7doVewk6HTb4vkH+NjgX4OpeLU24hVbGSFdK3T66QjpTaF3f0w6T4KdIga872C0xetC7cKduiF9RSkf2J/htnB8+/+nCGwca/oFK9OJiebs5dRU16JxUOf9UEq8lVsdWdfwg4fSw0bqWJLpAinXtGdWyJrVIj7HwHIWuxOQm4cXFu8DEkt4JjIpzZbe5/rwY478RVonYGj8BnS5eQmmVm0tZY5gmMn9a7lkeN88e+YLxYqyQnYIhQ4K+XqamDWs=
